version: 1.0.{build}

image:
  - Ubuntu

platform:
  - x64

environment:
  matrix:
    - CONFIGURATION: Release

install:
  - cd tools
  - sudo sh install_dependencies.sh
  - sh setup_prodg_linux.sh
  - cd ..

build_script:
  - make

test_script:
  - echo "No tests configured"
