version: 1.0.{build}

image:
  - Ubuntu

platform:
  - x64

environment:
  matrix:
    - CONFIGURATION: Release

install:
  - sudo sh tools/install_dependencies.sh
  - sudo sh tools/setup_prodg_linux.sh

build_script:
  - make

test_script:
  - echo "No tests configured"
