version: 1.0.{build}

image:
  - Ubuntu2004

platform:
  - x64

environment:
  matrix:
    - CONFIGURATION: Release

install:
  - sudo rm -f /var/lib/man-db/auto-update # makes build faster
  - cd scripts
  - sudo sh install_dependencies.sh
  - sh setup_progd_linux.sh
  - cd ..
  - pip3 install -r requirements.txt

build_script:
  - python3 configure.py
  - ninja

test_script:
  - echo "No tests configured"
