name: Sly Cooper May 19 2002 Prototype
sha1: 3e5fdf0c479a0f548e90b05d7fc558cd8e94f5c1

options:
  basename: sly1_may19
  target_path: disc/sly1_may19.elf
  elf_path: SCUS_971.98
  base_path: ../
  platform: ps2
  compiler: GCC

  asm_path: splat/may19/asm
  src_path: splat/may19/src
  build_path: build

  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/undefined_funcs_auto_may19.txt

  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/undefined_syms_auto_may19.txt

  symbol_addrs_path: config/symbol_addrs_may19.txt

  extensions_path: tools/splat_ext

  section_order: [".text", ".rodata", ".data", ".bss"]

  auto_all_sections: [".rodata", ".data", ".bss"]

subalign: 0x4

segments:
  - [0, databin, elf_header]

  - name: main
    type: code
    start: 0x001000
    vram: 0x100000
    bss_size: 0x3B1304
    subsegments:
    - [0x001000, asm, sce/crt0] # starts with 2 nops
    - [0x10c0, c, P2/ps2t/spaprops.ic]

    #----------------------------------------
    # Splice sources
    #----------------------------------------
    - [0x11de8, cpp, P2/splice/bif]
    - [0x19d50, cpp, P2/splice/eval]
    - [0x1b8f0, cpp, P2/splice/frame]
    - [0x1bde0, cpp, P2/splice/gc]
    - [0x1c6a8, cpp, P2/splice/method]
    - [0x1c6f8, cpp, P2/splice/pair]
    - [0x1c810, cpp, P2/splice/proc]
    - [0x1c890, cpp, P2/splice/ref]
    - [0x1d468, cpp, P2/splice/serialize]
    - [0x1d810, cpp, P2/splice/sidebag]
    - [0x1dbf8, cpp, P2/splice/spliceutils]
    - [0x1ddc0, cpp, P2/splice/splotheap]
    - [0x1e0f0, cpp, P2/splice/vecmat]

    #----------------------------------------
    # P2 sources
    #----------------------------------------
    - [0x1e888, c, P2/989snd]
    - [0x203e0, c, P2/brx]
    - [0x210a8, c, P2/ac]
    - [0x237c0, c, P2/act]
    - [0x25530, c, P2/actseg]
    - [0x25a08, c, P2/alarm]
    - [0x26548, c, P2/alo]
    - [0x2ecb0, c, P2/aseg]
    - [0x30d90, c, P2/asega]
    - [0x33520, c, P2/barrier]
    - [0x33a20, c, P2/bas]
    - [0x33e88, c, P2/basic]
    - [0x33f18, c, P2/bez]
    - [0x34d60, c, P2/binoc]
    - [0x3b480, c, P2/bis]
    - [0x3c960, c, P2/bbmark]
    - [0x3d468, c, P2/blend]
    - [0x3e098, c, P2/blip]
    - [0x3fd58, c, P2/bomb]
    - [0x40fc0, c, P2/bone]
    - [0x41278, c, P2/bq]
    - [0x41608, c, P2/break]
    - [0x42978, c, P2/bsp]
    - [0x43190, c, P2/button]
    - [0x45630, c, P2/cat]
    - [0x460e8, c, P2/can]
    - [0x46e10, c, P2/cd]
    - [0x47388, c, P2/chkpnt]
    - [0x47f48, c, P2/clip]
    - [0x49410, c, P2/clock]
    - [0x496c8, c, P2/cm]
    - [0x4cb58, c, P2/cnvo]
    - [0x4ce48, c, P2/coin]
    - [0x4f808, c, P2/cplcy]
    - [0x51578, c, P2/credit]
    - [0x51ac8, c, P2/crout]
    - [0x51f58, c, P2/crusher]
    - [0x52a50, c, P2/crv]
    - [0x54be8, c, P2/cycle]
    - [0x56770, c, P2/dart]
    - [0x571d8, c, P2/dartgun]
    - [0x58158, c, P2/dialog]
    - [0x595b0, c, P2/difficulty]
    - [0x59cf8, c, P2/dl]
    - [0x5a150, c, P2/dmas]
    - [0x5a838, c, P2/dsp]
    - [0x5ac98, c, P2/dysh]
    - [0x5b538, c, P2/dzg]
    - [0x5cb88, c, P2/emitter]
    - [0x62108, c, P2/eyes]
    - [0x625d0, c, P2/fader]
    - [0x627e0, c, P2/find]
    - [0x631e8, c, P2/flash]
    - [0x63468, c, P2/fly]
    - [0x64dd8, c, P2/font]
    - [0x677b8, c, P2/frm]
    - [0x68a30, c, P2/freeze]
    - [0x69480, c, P2/frzg]
    - [0x69590, c, P2/game]
    - [0x6a3f8, c, P2/geom]
    - [0x6a770, c, P2/gifs]
    - [0x6afd8, c, P2/glbs]
    - [0x6bff8, c, P2/glob]
    - [0x720f8, c, P2/gomer]
    - [0x729d0, c, P2/gs]
    - [0x748f8, c, P2/hg]
    - [0x75550, c, P2/hide]
    - [0x764a8, c, P2/hnd]
    - [0x76518, c, P2/ik]
    - [0x76e90, c, P2/jack]
    - [0x7b0d0, c, P2/jlo]
    - [0x7c478, c, P2/joy]
    - [0x7da08, c, P2/jt]
    - [0x866e8, c, P2/jp]
    - [0x880f8, c, P2/jsg]
    - [0x89630, c, P2/jump]
    - [0x8c068, c, P2/keyhole]
    - [0x8d170, c, P2/landing]
    - [0x8d250, c, P2/lgn]
    - [0x8fcd8, c, P2/lo]
    - [0x910d8, c, P2/light]
    - [0x92c48, c, P2/lookat]
    - [0x93028, c, P2/main]
    - [0x93b88, c, P2/map2d]
    - [0x93c78, c, P2/mark]
    - [0x96598, c, P2/mat]
    - [0x98840, c, P2/mecha]
    - [0x99c70, c, P2/mb]
    - [0x9aec0, c, P2/memcard]
    - [0x9aec8, c, P2/memory]
    - [0x9b608, c, P2/menu]
    - [0x9f7f0, c, P2/missile]
    - [0xa0770, c, P2/mouthgame]
    - [0xa1208, c, P2/mpeg]
    - [0xa2838, c, P2/mrkv]
    - [0xa2898, c, P2/ms]
    - [0xa2e00, c, P2/murray]
    - [0xa3410, c, P2/path]
    - [0xa4dd0, c, P2/phasemem]
    - [0xa4e28, c, P2/pipe]
    - [0xa4fc0, c, P2/pnt]
    - [0xa50d8, c, P2/po]
    - [0xa5c08, c, P2/prog]
    - [0xa6020, c, P2/prompt]
    - [0xa7750, c, P2/proxy]
    - [0xa7da0, c, P2/puffer]
    - [0xaa248, c, P2/pzo]
    - [0xac6e0, c, P2/rail]
    - [0xac7c0, c, P2/rat]
    - [0xade58, c, P2/rchm]
    - [0xaf900, c, P2/render]
    - [0xb0890, c, P2/rip]
    - [0xb69e0, c, P2/rog]
    - [0xbb3c0, c, P2/rope]
    - [0xbbc78, c, P2/rumble]
    - [0xbc000, c, P2/rwm]
    - [0xbd618, c, P2/sampler]
    - [0xbd970, c, P2/sc]
    - [0xbe370, c, P2/screen]
    - [0xc2d18, c, P2/sensor]
    - [0xc6018, c, P2/shadow]
    - [0xc6f08, c, P2/shape]
    - [0xc7190, c, P2/shd]
    - [0xc95e0, c, P2/shdanim]
    - [0xca988, c, P2/sky]
    - [0xcaa28, c, P2/slotheap]
    - [0xcac48, c, P2/sm]
    - [0xcbd98, c, P2/smartguard]
    - [0xcc968, c, P2/so]
    - [0xd1af8, c, P2/solve]
    - [0xd3580, c, P2/sort]
    - [0xd3710, c, P2/sound]
    - [0xd6570, c, P2/speaker]
    - [0xd6770, c, P2/spire]
    - [0xd6850, c, P2/splicemap]
    - [0xd6df8, c, P2/spliceobj]
    - [0xd8050, c, P2/sprbuf]
    - [0xd8640, c, P2/sqtr]
    - [0xd9060, c, P2/squish]
    - [0xd97a0, c, P2/step]
    - [0xdb4c0, c, P2/stepact]
    - [0xdb798, c, P2/stepcane]
    - [0xdc540, c, P2/stepguard]
    - [0xe1cf8, c, P2/stephang]
    - [0xe3838, c, P2/stephide]
    - [0xe5eb0, c, P2/steppipe]
    - [0xe7110, c, P2/steppower]
    - [0xe7628, c, P2/steprun]
    - [0xe8188, c, P2/stepside]
    - [0xe88b8, c, P2/stepski]
    - [0xe9e30, c, P2/stepzap]
    - [0xec048, c, P2/stream]
    - [0xec360, c, P2/suv]
    - [0xf0788, c, P2/sw]
    - [0xf32e8, c, P2/tail]
    - [0xf3e28, c, P2/tank]
    - [0xf5940, c, P2/target]
    - [0xf5b88, c, P2/text]
    - [0xf78b8, c, P2/thread]
    - [0xf7b38, c, P2/tn]
    - [0xfa030, c, P2/transition]
    - [0xfa758, c, P2/turret]
    - [0xfb1b0, c, P2/tv]
    - [0xfdec8, c, P2/ub]
    - [0xff688, c, P2/ui]
    - [0x1005b0, c, P2/update]
    - [0x100ef0, c, P2/util]
    - [0x102000, c, P2/vec]
    - [0x102cc8, c, P2/vife]
    - [0x10a658, c, P2/vifs]
    - [0x10ac98, c, P2/vis]
    - [0x10b070, c, P2/water]
    - [0x10be78, c, P2/waypoint]
    - [0x10c398, c, P2/wibu_ee]
    - [0x10c4e8, c, P2/wipe]
    - [0x10cd18, c, P2/wm]
    - [0x10ee10, c, P2/wr]
    - [0x110338, c, P2/xform]
    - [0x111da0, c, P2/zap]

    #----------------------------------------

    - [0x113e00, data]

    - [0x12e900, bin, vutext]

    - [0x192d00, rodata]

  - [0x1a1f80, databin]
  - [0xBC8E6D]
