name: Sly Cooper and the Thievius Raccoonus (USA)
sha1: 57dc305db57932ad3f1122966cdb695d2e62a47a

options:
  basename: sly1
  target_path: disc/SCUS_971.98
  elf_path: SCUS_971.98
  base_path: ../
  platform: ps2
  compiler: GCC

  asm_path: splat/release/asm
  src_path: splat/release/src
  build_path: build

  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt

  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/undefined_syms_auto.txt

  symbol_addrs_path: config/symbol_addrs.txt

  extensions_path: tools/splat_ext

  section_order: [".text", ".rodata", ".data", ".bss"]

  auto_all_sections: [".rodata", ".data", ".bss"]

subalign: 0x4

segments:
  - [0, databin, elf_header]

  - name: main
    type: code
    start: 0x001000
    vram: 0x100000
    bss_size: 0x3B1304
    subsegments:
    - [0x001000, asm, sce/crt0] # starts with 2 nops
    - [0x001178, c, P2/ps2t/spaprops] # ext should be .ic

    #----------------------------------------
    # Splice sources
    #----------------------------------------
    - [0x013698, cpp, P2/splice/bif]
    - [0x019d48, cpp, P2/splice/eval]
    - [0x01b328, cpp, P2/splice/frame]
    - [0x01b678, cpp, P2/splice/gc]
    - [0x01bdf8, asm]

    #----------------------------------------
    # P2 sources
    #----------------------------------------
    - [0x0491A0, c, P2/coin]
    - [0x049400, asm] # TBD

    - [0x0eb408, c, P2/util]
    - [0x0ec518, asm] # TBD

    #----------------------------------------

    - [0x112E10, bin, vutext]

    - [0x118380, rodata]

    - [0x151580, data]

  - [0x17C200, databin]
  - [0x1A20D0]
